# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f59a70b4865239d9f8f512041b666bc7ce1de486cf82eae7bdccc63a995b89b72d0314197a9887a0116b45588c4605fce26b012b2173df8eb7182717ca946f9b

test:
  secret_key_base: 9bf4a83b2d23c42c60cfbdcefe399610294b3e6cdea126b47c645001784f6946f9f48d3fb2727870bab874687a5b03b4070ec9bfaa911753db8bac3c8aa7b23b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
